#ifndef _WFL_DEFINITIONS_H
#define _WFL_DEFINITIONS_H

#define WFL_SSID_MAX_LENGTH 32
#define WFL_WPA_KEY_MAX_LENGTH 63
#define WFL_WEP_KEY_MAX_LENGTH 13
#define WFL_MAC_ADDR_LENGTH 6
#define WFL_IPV4_LENGTH 4
#define WFL_NETWORKS_LIST_MAXNUM 10
#define MAX_SOCK_NUM  4
#define SOCK_NOT_AVAIL  255
#define NA_STATE -1
#define WFL_MAX_ATTEMPT_CONNECTION 10

typedef enum {
    WFL_NO_SHIELD = 255,
    WFL_IDLE_STATUS = 0,
    WFL_NO_SSID_AVAIL,
    WFL_SCAN_COMPLETED,
    WFL_CONNECTED,
    WFL_CONNECT_FAILED,
    WFL_CONNECTION_LOST,
    WFL_DISCONNECTED
} wfl_status_t;

enum wfl_enc_type {
    ENC_TYPE_WEP  = 5,
    ENC_TYPE_TKIP = 2,
    ENC_TYPE_CCMP = 4,
    ENC_TYPE_NONE = 7,
    ENC_TYPE_AUTO = 8
};

#endif
